const crypto = require('crypto');

const animals = [
    { id: '120', name: 'Manchot', file: 'Emperor_Penguin_Manchot_empereur.jpg' },
    { id: '121', name: 'Autruche', file: 'Struthio_camelus_01.jpg' },
    { id: '319', name: 'Méduse', file: 'Kompaktqualle_Rhizostoma_pulmo.jpg' },
    { id: '341', name: 'Sauterelle', file: 'Tettigonia_viridissima_male_01.jpg' },
    { id: '342', name: 'Grillon', file: 'Gryllus_campestris_MHNT.jpg' },
    { id: '343', name: 'Guêpe', file: 'Common_wasp_Vespula_vulgaris.jpg' },
    { id: '344', name: 'Bourdon', file: 'Bombus_terrestris_1.jpg' },
    { id: '345', name: 'Fourmi', file: 'Formica_rufa_side_01.jpg' },
    { id: '346', name: 'Mouche', file: 'House_fly_June_2008-1.jpg' },
    { id: '347', name: 'Araignée', file: 'Araneus_diadematus_(aka).jpg' },
    { id: '348', name: 'Mygale', file: 'Lasiodora_parahybana_2009_G03.jpg' },
    { id: '349', name: 'Scorpion', file: 'Pandinus_imperator_2.jpg' },
    { id: '350', name: 'Baleine', file: 'Humpback_Whale_underwater_shot.jpg' },
    { id: '351', name: 'Cachalot', file: 'Mother_and_baby_sperm_whale.jpg' },
    { id: '352', name: 'Orque', file: 'Killerwhales_jumping.jpg' },
    { id: '353', name: 'Narval', file: 'Narve.jpg' },
    { id: '354', name: 'Beluga', file: 'Beluga03.jpg' },
    { id: '355', name: 'Thon', file: 'Thunnus_thynnus.jpg' },
    { id: '356', name: 'Saumon', file: 'Salmon_male.jpg' },
    { id: '383', name: 'Truite', file: 'Salmo_trutta_fario_01.jpg' },
    { id: '384', name: 'Carpe', file: 'Common_carp.jpg' },
    { id: '385', name: 'Brochet', file: 'Esox_lucius1.jpg' },
    { id: '386', name: 'Silure', file: 'Freischwimmender_Wels.jpg' },
    { id: '387', name: 'Poisson rouge', file: 'Goldfish3.jpg' },
    { id: '388', name: 'Combattant', file: 'Betta_splendens_male_with_bubble_nest.jpg' },
    { id: '389', name: 'Guppy', file: 'Poecilia_reticulata_male_02.jpg' },
    { id: '390', name: 'Crevette', file: 'Palaemon_serratus.jpg' },
    { id: '391', name: 'Langouste', file: 'Palinurus_elephas.jpg' },
    { id: '392', name: 'Bernard-l\'ermite', file: 'Pagurus_bernhardus.jpg' },
    { id: '393', name: 'Oursin', file: 'Paracentrotus_lividus_01.jpg' },
    { id: '394', name: 'Corail', file: 'Coral_Outcrop_Flynn_Reef.jpg' },
    { id: '395', name: 'Anémone', file: 'Anemone_with_clown_fish.jpg' },
    { id: '396', name: 'Termite', file: 'Coptotermes_formosanus_shiraki_USGov_k8204-7.jpg' },
    { id: '397', name: 'Taon', file: 'Tabanus_autumnalis_01.jpg' },
    { id: '398', name: 'Punaise', file: 'Palomena_prasina_01.jpg' },
    { id: '399', name: 'Perce-oreille', file: 'Forficula_auricularia_male.jpg' },
    { id: '400', name: 'Tique', file: 'Ixodes_ricinus_01.jpg' },
    { id: '401', name: 'Mille-pattes', file: 'Cylindroiulus_caeruleocinctus_01.jpg' },
    { id: '402', name: 'Scolopendre', file: 'Scolopendra_cingulata_01.jpg' },
    { id: '456', name: 'Lucane', file: 'Lucanus_cervus_male_01.jpg' },
    { id: '457', name: 'Hanneton', file: 'Melolontha_melolontha_01.jpg' },
    { id: '458', name: 'Doryphore', file: 'Leptinotarsa_decemlineata_01.jpg' },
    { id: '459', name: 'Capricorne', file: 'Cerambyx_cerdo_01.jpg' },
    { id: '460', name: 'Dynaste Hercule', file: 'Dynastes_hercules_hercules_male.jpg' },
    { id: '461', name: 'Gendarme', file: 'Pyrrhocoris_apterus_01.jpg' },
    { id: '462', name: 'Chrysope', file: 'Chrysopa_perla_01.jpg' },
    { id: '463', name: 'Syrphe', file: 'Syrphid_fly_June_2011-1.jpg' },
    { id: '464', name: 'Bombyle', file: 'Bombylius_major_01.jpg' },
    { id: '465', name: 'Sphinx tête de mort', file: 'Acherontia_atropos_01.jpg' },
    { id: '466', name: 'Paon du jour', file: 'Aglais_io_01.jpg' },
    { id: '467', name: 'Machaon', file: 'Papilio_machaon_01.jpg' },
    { id: '468', name: 'Morio', file: 'Nymphalis_antiopa_01.jpg' },
    { id: '469', name: 'Taupe-grillon', file: 'Gryllotalpa_gryllotalpa_01.jpg' },
    { id: '470', name: 'Puce', file: 'Flea_01.jpg' },
    { id: '471', name: 'Pou', file: 'Pediculus_humanus_capitis_01.jpg' },
    { id: '472', name: 'Glomeris', file: 'Glomeris_marginata_01.jpg' },
    { id: '473', name: 'Cloporte', file: 'Armadillidium_vulgare_01.jpg' },
    { id: '474', name: 'Lepisme', file: 'Lepisma_saccharina_01.jpg' },
    { id: '475', name: 'Blatte', file: 'Blatella_germanica_01.jpg' },
    // BATCH 5: Reptiles & Amphibians
    { id: '330', name: 'Crocodile', file: 'Nile_crocodile_head.jpg' },
    { id: '331', name: 'Tortue verte', file: 'Chelonia_mydas_01.jpg' },
    { id: '357', name: 'Python', file: 'Python_regius_01.jpg' },
    { id: '358', name: 'Cobra', file: 'Naja_naja_01.jpg' },
    { id: '359', name: 'Lézard', file: 'Podarcis_muralis_01.jpg' },
    { id: '360', name: 'Dragon de Komodo', file: 'Varanus_komodoensis_01.jpg' },
    { id: '433', name: 'Cécilie', file: 'Siphonops_annulatus_01.jpg' },
    { id: '434', name: 'Protée', file: 'Proteus_anguinus_01.jpg' },
    { id: '435', name: 'Salamandre géante', file: 'Andrias_davidianus_01.jpg' },
    { id: '436', name: 'Grenouille taureau', file: 'Lithobates_catesbeianus_01.jpg' },
    { id: '437', name: 'Alyte accoucheur', file: 'Alytes_obstetricans_01.jpg' },
    { id: '438', name: 'Sonneur', file: 'Bombina_variegata_01.jpg' },
    { id: '439', name: 'Pipa pipa', file: 'Pipa_pipa_01.jpg' },
    { id: '440', name: 'Grenouille de verre', file: 'Hyalinobatrachium_fleischmanni_01.jpg' },
    { id: '441', name: 'Grenouille tomate', file: 'Dyscophus_antongilii_01.jpg' },
    { id: '442', name: 'Dendrobate bleu', file: 'Dendrobates_azureus_01.jpg' },
    { id: '443', name: 'Basilic', file: 'Basiliscus_plumifrons_01.jpg' },
    { id: '444', name: 'Moloch', file: 'Moloch_horridus_01.jpg' },
    { id: '445', name: 'Monstre de Gila', file: 'Heloderma_suspectum_01.jpg' },
    { id: '446', name: 'Tuatara', file: 'Sphenodon_punctatus_01.jpg' },
    { id: '447', name: 'Tortue alligator', file: 'Macrochelys_temminckii_01.jpg' },
    { id: '448', name: 'Mamba noir', file: 'Dendroaspis_polylepis_01.jpg' },
    { id: '449', name: 'Vipère heurtante', file: 'Bitis_arietans_01.jpg' },
    { id: '450', name: 'Serpent corail', file: 'Micrurus_fulvius_01.jpg' },
    { id: '451', name: 'Anolis', file: 'Anolis_carolinensis_01.jpg' },
    { id: '452', name: 'Tortue luth', file: 'Dermochelys_coriacea_01.jpg' },
    { id: '453', name: 'Tortue de Floride', file: 'Trachemys_scripta_elegans_01.jpg' },
    { id: '454', name: 'Gecko à crête', file: 'Correlophus_ciliatus_01.jpg' },
    { id: '455', name: 'Varan du Nil', file: 'Varanus_niloticus_01.jpg' },
    { id: '476', name: 'Crapaud commun', file: 'Bufo_bufo_01.jpg' },
    { id: '477', name: 'Couleuvre à collier', file: 'Natrix_natrix_01.jpg' },
    { id: '478', name: 'Salamandre tachetée', file: 'Salamandra_salamandra_01.jpg' },
    { id: '479', name: 'Triton', file: 'Lissotriton_vulgaris_01.jpg' }
];

function getWikimediaUrl(filename) {
    const fixedFilename = filename.replace(/ /g, '_');
    const hash = crypto.createHash('md5').update(fixedFilename).digest('hex');
    const a = hash[0];
    const ab = hash.substring(0, 2);
    return `https://upload.wikimedia.org/wikipedia/commons/thumb/${a}/${ab}/${fixedFilename}/500px-${fixedFilename}`;
}

animals.forEach(a => {
    console.log(`ID: ${a.id} | Name: ${a.name} | URL: ${getWikimediaUrl(a.file)}`);
});
